import { type NextPage } from "next";
import Head from "next/head";
import { signIn, signOut, useSession } from "next-auth/react";

import { api } from "~/utils/api";
import Navbar from "~/components/Navbar";
import Search from "~/components/Search";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Kitchen Genie</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex h-screen">
        <Navbar />
        <main className="w-full">
          <div className="flex h-full items-start justify-center py-20 px-5">
            <Search />
          </div>
        </main>
      </div>
    </>
  );
};

export default Home;
