import { type NextPage } from "next";
import Head from "next/head";
import { signIn, signOut, useSession } from "next-auth/react";

import { api } from "~/utils/api";
import Navbar from "~/components/Navbar";
import Search from "~/components/Search";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Kitchen Genie</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className="flex h-full items-center justify-center">
        <Search />
      </div>
    </>
  );
};

export default Home;
