import { type NextPage } from "next";
import Head from "next/head";
import { signIn, signOut, useSession } from "next-auth/react";

import { api } from "~/utils/api";
import Navbar from "~/components/Navbar";
import Search from "~/components/Search";

const Recipes: NextPage = () => {
  const { data: sessionData } = useSession();

  const { data: recipe, refetch: refetchRecipe } = api.recipe.getAll.useQuery(
    undefined, // no params
    {
      enabled: sessionData?.user !== undefined,
    }
  );

  return (
    <>
      <Head>
        <title>Your Recipes</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className="flex h-full min-h-screen w-full flex-col items-center justify-start gap-10 py-20 px-5">
        <div className="prose h-full w-full">
          <h1>Your Recipes</h1>
          {JSON.stringify(recipe)}
        </div>
      </main>
    </>
  );
};

export default Recipes;
